version: '3.9'

services:
  postgres:
    image: postgres:14
    #    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
#    networks:
#      - backend
#  web:
#    build: .
#    ports:
#      - 80:80
#      - 443:443
#    environment:
#      - CADDY_INGRESS_NETWORKS=caddy
#    networks:
#      - caddy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - caddy_data:/data
#    restart: unless-stopped


volumes:
  db_data:

networks:
  caddy:
    external: true
  backend:
