"""empty message

Revision ID: 555a529cdd73
Revises: e4073800ea7a
Create Date: 2022-06-01 15:52:36.139735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555a529cdd73'
down_revision = 'e4073800ea7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.String(length=100), nullable=True),
    sa.Column('end_time', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
